#!/usr/bin/env ruby
require "pressy"

def main
  store = Pressy::Store::FileStore.new(Dir.pwd)
  site = Pressy::Site.new(store)

  action = ARGV.shift
  raise "no action given" unless action

  case action.to_sym
  when :pull
    Pressy::Command::Pull.new(site, $stderr).run
  when :push
    Pressy::Command::Push.new(site, $stderr).run
  else
    raise "unexpected action '#{action}'"
  end
end

main
