#!/usr/bin/env ruby
require "pressy"

def main
  store = Pressy::Store::FileStore.new(Dir.pwd)
  site = Pressy::Site.new(store)

  action = ARGV.shift&.to_sym

  runner = Pressy::Command::Runner.new(site, $stderr)
  runner.register(Pressy::Command::Pull)
  runner.register(Pressy::Command::Push)
  runner.run(action)
end

main
