#!/usr/bin/env ruby
require "pressy"

store = Pressy::Store::FileStore.new(Dir.pwd)
site = Pressy::Site.new(store)

action = ARGV.shift
raise "no action given" unless action

case action.to_sym
when :pull
  result = site.pull
  if result.has_changes?
    $stderr.puts "Updated #{result.changed_posts.count} posts."
  else
    $stderr.puts "Already up-to-date."
  end
else
  raise "unexpected action '#{action}'"
end
